---
- name: Base set up
  hosts: all
  become: yes
  tasks:

  #Установка приложений на RedHat-based системах
  - name: install software on CentOS
    yum:
      name:
        - vim
        - traceroute
        - tcpdump
        - net-tools
      state: present
      update_cache: true
    when: (ansible_os_family == "RedHat")
  
  #Установка приложений на Debian-based системах
  - name: install software on Debian-based
    apt:
      name: 
        - vim
        - traceroute
        - tcpdump
        - net-tools
      state: present
      update_cache: true
    when: (ansible_os_family == "Debian")

  - name: Copy ifcfg-vlan1 to testClient1 and testServer1
    copy:
      src: temp/ifcfg-vlan1.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-vlan1
    when: (ansible_hostname == "testClient1" or ansible_hostname == "testServer1") 

  - name: restart NetworkManager testClient1 and testServer1
    service: 
        name: NetworkManager 
        state: restarted 
        enabled: yes
    when: (ansible_hostname == "testClient1" or ansible_hostname == "testServer1") 

  - name: Copy 50-cloud-init to testClient2 and testServer2
    copy:
      src: temp/50-cloud-init.yaml.j2
      dest: /etc/netplan/50-cloud-init.yaml
    when: (ansible_hostname == "testClient2" or ansible_hostname == "testServer2") 

  - name: restart Network testClient2 and testServer2
    shell: netplan apply 
    when: (ansible_hostname == "testClient2" or ansible_hostname == "testServer2") 

  - name: set up ifcfg-bond0 to inetRouter and centralRouter
    copy:
      src: temp/ifcfg-bond0.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-bond0
    when: (ansible_hostname == "inetRouter" or ansible_hostname == "centralRouter") 

  - name: set up eth1,eth2 to inetRouter and centralRouter
    copy: 
      src: "{{ item }}" 
      dest: /etc/sysconfig/network-scripts/
      owner: root
      group: root
      mode: 0644
    with_items:
      - temp/ifcfg-eth1
      - temp/ifcfg-eth2
    when: (ansible_hostname == "inetRouter" or ansible_hostname == "centralRouter") 

  - name: restart NetworkManager inetRouter and centralRouter
    service: 
        name: NetworkManager 
        state: restarted 
        enabled: yes
    when: (ansible_hostname == "inetRouter" or ansible_hostname == "centralRouter")